version: '3.7'
networks:
  redpanda_network:
    driver: bridge
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - redpanda_network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  kafka:
    image: weimeilin/migratekafka:latest
    networks:
      - redpanda_network
    depends_on:
      - zookeeper
    ports:
      - 29094:29094
      - 9094:9094
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9094,PLAINTEXT_HOST://localhost:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #apicurio:
  #  image: apicurio/apicurio-registry-mem:2.4.x-snapshot
  #  networks:
  #    - redpanda_network
  #  ports:
  #    - 8081:8080
  #  depends_on:
  #    - kafka
  #  environment:
  #    QUARKUS_PROFILE: prod
  schemaregistry:
    image: confluentinc/cp-schema-registry:5.1.2
    restart: always
    networks:
      - redpanda_network
    depends_on:
      - zookeeper
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
      SCHEMA_REGISTRY_HOST_NAME: schemaregistry
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
    ports:
      - 8081:8081